### ISSUE TITLE
throw permission denied error

### ISSUE THREAD

**Issue by logicminds** [Nanosim-LIG/opencl-ruby#13]
Rather than just a plain OpenCL error I would like to see a permission denied error thrown when trying to use opencl. 

```
[6] pry(main)> OpenCL.platforms.first.devices
OpenCL::Error::DEVICE_NOT_FOUND: -1
```

**Comment by Kerilk** [comment]
As you can see here:
https://github.com/Nanosim-LIG/opencl-ruby/blob/9f1efde007b75a33812523b74f8ecfea08e34fad/opencl_ruby_ffi/lib/opencl_ruby_ffi/Platform.rb#L111-L121
and there:
https://www.khronos.org/registry/OpenCL//sdk/2.2/docs/man/html/clGetDeviceIDs.html
the underlying OpenCL call (clGetDeviceIDs) is only returning me an OpenCL error code. I have no access to why it cannot find a device. It could be because none of the devices match the type (obviously `Device::Type::ALL` should cover everything), or it could be because no device for the specific platform is installed (though in this case the platform maybe shouldn't register itself), or other reasons I cannot fathom right now.

We can try working out a solution for your problem if you can devise a way to catch the underlying error.

**Comment by logicminds** [comment]
What is this doing? OpenCL.clGetDeviceIDs  I know a way we can check this but it involves reading the /proc filesystem on linux and thus is not cross platform.

**Comment by Kerilk** [comment]
`OpenCL.clGetDeviceIDs` calls the `clGetDeviceIDs` function from the libOpenCL.so (libOpenCL.dll on windows) using FFI (https://github.com/ffi/ffi), the function import is done here:
https://github.com/Nanosim-LIG/opencl-ruby/blob/9f1efde007b75a33812523b74f8ecfea08e34fad/opencl_ruby_ffi/lib/opencl_ruby_ffi/opencl_ruby_ffi_base_gen.rb#L1845
The libOpenCL.so then forwards the call to the vendor library's implementation of `clGetDeviceIDs` by using the dispatch table of the `cl_platform_id platform` argument.
See:
https://www.khronos.org/registry/OpenCL//sdk/2.2/docs/man/html/clGetDeviceIDs.html
https://www.khronos.org/registry/OpenCL/specs/2.2/html/OpenCL_Ext.html#cl_khr_icd-opencl
